*augment the list of WOS journal abbreviations
* read in the two files of synonyms I generated by hand
foreach x in larger small {
 import excel using correctjournalnojournalscore-`x'sample.xlsx, clear firstrow
 keep journal journalabbrev
 drop if missing(journalabbrev)
 duplicates drop
 save journalabbrevsbyhand-`x', replace
}
* combine those with the existing file and remove duplicates
import delimited using journalabbrevs.tsv, clear
rename v1 journal
rename v2 journalabbrev
foreach x in larger small {
 append using journalabbrevsbyhand-`x'
}
replace journal = trim(journal)
replace journalabbrev = trim(journalabbrev)
duplicates drop
export delimited using journalabbrevs-extended.tsv, delim(tab) novar replace
